version: "3.8"

services:
  api-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cluster-api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
